### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Samyssmile** [dnyaneshwargiri/keycloak-angular-integration#1]
Because of Angular SSR. The window object in your keycloak init not existing. Because its executed in angulars server side. How to solve it?

```
15:22:28 [vite] Internal server error: window is not defined
```

**Comment by dnyaneshwargiri** [comment]
@Samyssmile this seems to be same issue described here. 
https://github.com/mauriciovigolo/keycloak-angular/issues/29
