### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Samyssmile** [dnyaneshwargiri/keycloak-angular-integration#2]
Hi,

I reopened a ticket because, for some reason, you closed the last one.

After extensive debugging of your code to understand why it works with your repository and nobody else's, I found the cause.

You created a Server-Side Rendering (SSR) Angular app. Because of this, it's not possible for your 'keycloak-init.factory.ts' to work since it uses the window object, which is not available on the server.

So, I started investigating how you worked around this.

In your 'angular.json', you use:

```
  "prerender": false,
  "ssr": false
```

This makes no sense and is very confusing. The people on YouTube who commented on your video with the same bug as me ran into the same problem.

Why did you create an SSR Angular app and then deactivate it?

However, if you change your incorrect configuration to the correct one:

```
    "prerender": true,
    "ssr": {
      "entry": "server.ts"
    }
```

You can reproduce the bug.

Please don't close this issue. Maybe we can find a solution together and pin it to your video on YouTube.

# Possible solution for window is undefined bug.
But this will lead to next bug: ERROR Error: An error happened during access validation. Details:TypeError: Cannot read properties of undefined (reading 'resourceAccess')
I not have a solution for that.

```import {KeycloakService} from 'keycloak-angular';
import {isPlatformBrowser} from '@angular/common';
import {environment} from "../../environments/environment";

export function initializeKeycloak(keycloak: KeycloakService, platformId: Object): () => Promise<boolean> {

  return () => {
    if (isPlatformBrowser(platformId)) { 
      return keycloak.init({
        config: {
          url: environment.keycloakUrl,
          realm: environment.keycloakRealm,
          clientId: environment.keycloakClientId,

        },
        enableBearerInterceptor: true,
        bearerPrefix: 'Bearer',
        bearerExcludedUrls: ['/assets'],
        initOptions: {
          onLoad: 'login-required',
          checkLoginIframe: false,
          enableLogging: true,
        },
      });
    } else {
      return Promise.resolve(true);
    }
  };
}
````

**Comment by dnyaneshwargiri** [comment]
@Samyssmile I really appreciate your investigation. This was never meant to be  SSR enabled app from my intension as far as know. Also I think issue is probably same tagged in previous issue https://github.com/mauriciovigolo/keycloak-angular/issues/29 i which i closed. Reproducing it will give clear idea though. Thank you!

**Comment by Samyssmile** [comment]
https://github.com/mauriciovigolo/keycloak-angular/issues/539
